#!/bin/bash
tremux
echo -e "\e[1;34m[MB-5×1] جاري التحقق من الربط الإجباري...\e[0m"
if [ -d "node_modules/react-router-dom" ]; then
    echo -e "\e[1;32m✅ تم ربط التطبيقات بنجاح.\e[0m"
else
    echo -e "\e[1;31m❌ فشل الربط، أعد محاولة التثبيت.\e[0m"
fi
npx tsc --noEmit
