github.com:
    users:
        dealssmart389-collab:
            oauth_token: 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
    git_protocol: https
    user: dealssmart389-collab
    oauth_token: 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
